version: "3.8"
services:
  nsp_backend:
    container_name: nsp_backend
    image: daew/nsp-template:0.0.2
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - USER=admindaew
      - PASSWORD=pass
      - DATABASE=nps_database
      - HOST=nsp_db # NAME OF THE SERVICE
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "54321:54321"
    environment:
      - POSTGRES_USER=admindaew
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nps_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}